apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube
  labels:
    app: hello-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
      - name: hello-kube
        image: mz026/hello-kube:0.2
        ports:
          - containerPort: 3000
